#!/usr/bin/env bash
#script that transfers a file from our client to a server
# check if parameters are lest than 4

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Variables assiged to paremeters

path_to_filev=$1
ip=$2
username=$3
path_to_ssh_pkey=$4

# disable strict host checking

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_pkey" "$path_to_file" "$usrname@ip:~/"

#checking if the transfert was successful
if [ $? -eq 0 ]
then
	echo "File transfered successfully"
else
	echo "File tranfer failed"
fi
