#!/usr/bin/env bash
# Commands to install Nginx on my Web-Sever-01

# Updating Packages before Installations
sudo apt-get update
sudo apt-get -y install nginx

# Configuring the (UFW) to allow incoming traffic for the Nginx HTTP service
sudo ufw allow 'Nginx HTTP'

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing and start Nginx configurations for Syntax errors
sudo nginx -t
sudo service nginx start
