#!/usr/bin/env bash
# Script that configures a new Ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name_;\n\trewrite ^\/redirect_me https:\/\/github.com\/MbaliFelecia permanent;/" /etc/nginx/sites-available/defult
sudo sed -i "s/server_name_;/$string_for_replacement/" /etc/nginx/sites-enabled/defult

sudo service nginx restart
