#!/usr/bin/env bash
# Script that configures a new Ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx

# code to redirect a specific endpoint
echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name_;\n\trewrite ^\/redirect_me https:\/\/github.com\/MbaliFelecia permanent;/" /etc/nginx/sites-available/defult
sudo sed -i "s/server_name_;/$string_for_replacement/" /etc/nginx/sites-enabled/defult

# code to create error page and add a redirect for error 404
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
string_for_replacement="listen 80 defult_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-available/default

# restart the server
sudo service nginx restart 
