#!/usr/bin/env bash
# Bash script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers

# update and install HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# Configuration file
server_config=\
"
frontend  MbaliFelecia_frontend
        bind *:80
        mode http
        default_backend MbaliFelecia_backend
backend MbaliFelecia_backend
        balance roundrobin
        server 277050-web-01 100.26.221.159:80 check
        server 277050-web-02 18.214.89.45:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
