#!/usr/bin/env bash
# nginx server configuration to listen to prot 80

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start 
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
