#!/usr/bin/env bash
# This script print "Best school" 10 time 
# and prints hi if 9th iteration using if statement
i=0
while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	((i++))
done
